(define (mod a b) (remainder a b))
;(define (floor a)

(define (f n)
  (let* (
         (t (floor (/ n 50)))
         (h (floor (/ (+ n 25) 50)))
         (i (floor (/ n 10)))
         (j (floor (/ (+ n 5) 10)))
         (a (mod i 5))
         (b (mod (+ j 2) 5))
         (k (floor (/ n 5)))
         (c (mod k 10))
         (d (mod (+ k 5) 10))
         )
    (+
     (* (/ 25 12) t t (- t 1) (- t 1))
     (* (/ (* 5 (+ a 6)) 6) t (- t 1) (- (* t 2) 1))
     (* (/ (* 5 (- (* a 9) 11)) 6) t (- t 1))
     (* (+ c 1) 
        (+ (* (/ 5 6) t t t)
           (* (/ (+ a 6) 2) t t)
           (* (/ (- (* a 9) 11) 6) t)
           ))
     (* (/ 25 12) h h (- h 1) (- h 1))
     (* (/ (* 5 (+ b 1)) 6) h (- h 1) (- (* h 2) 1))
     (* (/ (* 5 (- (* b 3) 2)) 6) h (- h 1))
     (* (+ d 1) 
        (+ (* (/ 5 6) h h h)
           (* (/ (+ b 1) 2) h h)
           (* (/ (- (* b 3) 2) 6) h)
           ))
     )
    );let
  )
